-- KERN persistent storage schema
-- Run this in the SQL editor of a dedicated KERN Supabase project.
--
-- KERN only accesses these tables from authenticated server routes using a
-- Supabase secret key. anon/authenticated access is intentionally revoked.

create table if not exists public.kern_todos (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 500),
  project text not null default 'KERN' check (char_length(project) between 1 and 120),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'critical')),
  done boolean not null default false,
  due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kern_incidents (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  resource text not null,
  status text not null check (status in ('open', 'resolved')),
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kern_alerts (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  severity text not null check (severity in ('info', 'warning', 'critical')),
  title text not null,
  body text,
  status text not null default 'open' check (status in ('open', 'acknowledged', 'resolved')),
  fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.kern_audit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  resource text,
  outcome text not null default 'success' check (outcome in ('success', 'failure')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.kern_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists kern_todos_done_created_idx
  on public.kern_todos (done, created_at desc);

create index if not exists kern_incidents_status_started_idx
  on public.kern_incidents (status, started_at desc);

create index if not exists kern_alerts_status_created_idx
  on public.kern_alerts (status, created_at desc);

create index if not exists kern_alerts_fingerprint_idx
  on public.kern_alerts (fingerprint)
  where fingerprint is not null;

create index if not exists kern_audit_events_created_idx
  on public.kern_audit_events (created_at desc);

alter table public.kern_todos enable row level security;
alter table public.kern_incidents enable row level security;
alter table public.kern_alerts enable row level security;
alter table public.kern_audit_events enable row level security;
alter table public.kern_settings enable row level security;

revoke all on table public.kern_todos from anon, authenticated;
revoke all on table public.kern_incidents from anon, authenticated;
revoke all on table public.kern_alerts from anon, authenticated;
revoke all on table public.kern_audit_events from anon, authenticated;
revoke all on table public.kern_settings from anon, authenticated;

grant select, insert, update, delete on table public.kern_todos to service_role;
grant select, insert, update, delete on table public.kern_incidents to service_role;
grant select, insert, update, delete on table public.kern_alerts to service_role;
grant select, insert, update, delete on table public.kern_audit_events to service_role;
grant select, insert, update, delete on table public.kern_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.kern_todos is 'Persistent KERN developer TODOs';
comment on table public.kern_incidents is 'KERN uptime/deployment incident history';
comment on table public.kern_alerts is 'KERN operational alerts';
comment on table public.kern_audit_events is 'KERN control-plane and data mutation audit trail';
comment on table public.kern_settings is 'KERN persistent non-secret settings';
